# Generated by Django 3.0.6 on 2020-06-06 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200528_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('index', models.IntegerField(default=1000, verbose_name='播放顺序')),
                ('t_publish', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('jmp_url', models.URLField(verbose_name='跳转地址')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='邮箱验证码')),
                ('email', models.CharField(max_length=40, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('findback', '找回密码')], max_length=20)),
                ('send_time', models.DateField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blog_num',
            field=models.IntegerField(default=0, verbose_name='微博数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fans_num',
            field=models.IntegerField(default=0, verbose_name='粉丝数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='follow_num',
            field=models.IntegerField(default=0, verbose_name='关注数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '保密')], default='U', max_length=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='message_nums',
            field=models.IntegerField(default=0, verbose_name='未读消息数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='t_publish',
            field=models.DateField(default=datetime.datetime.now, verbose_name='加入时间'),
        ),
    ]
