# Generated by Django 3.0.6 on 2020-06-05 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(default='', max_length=50, verbose_name='话题名称')),
                ('topic_blogs_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='相关微博数')),
                ('t_publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微博话题',
                'verbose_name_plural': '微博话题',
            },
        ),
        migrations.CreateModel(
            name='MiniBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='发布状态')),
                ('t_publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('t_update', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', markdownx.models.MarkdownxField(blank=True, max_length=2500, verbose_name='正文 :')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='图片')),
                ('num_click', models.IntegerField(blank=True, default=0, null=True, verbose_name='微博点击数')),
                ('num_likes', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('num_comment', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数')),
                ('num_fav', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数')),
                ('has_pic', models.IntegerField(blank=True, default=0, null=True, verbose_name='是否有图')),
                ('need_unfold', models.IntegerField(choices=[(0, '不需展开'), (1, '需要展开且未展开'), (2, '需展开且已展开')], default=0)),
                ('related_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aphor.Topic', verbose_name='微博相关话题')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miniblog_set', to=settings.AUTH_USER_MODEL, verbose_name='发布用戶')),
            ],
            options={
                'verbose_name': '微博',
                'verbose_name_plural': '微博',
                'ordering': ('-t_publish',),
            },
        ),
    ]
