# Generated by Django 3.0.6 on 2020-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aphor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniblog',
            name='image',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='blogImage/', verbose_name='图片'),
        ),
    ]
