# Generated by Django 3.0.6 on 2020-06-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aphor', '0002_auto_20200605_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='static/upload_multi_img/', verbose_name='图片')),
                ('images_list', models.CharField(max_length=10000, verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='miniblog',
            name='image',
        ),
        migrations.AddField(
            model_name='miniblog',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='blogImage/', verbose_name='图片'),
        ),
    ]
