# Generated by Django 3.0.6 on 2020-06-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aphor', '0003_auto_20200605_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniblog',
            name='images',
        ),
    ]
