# Generated by Django 3.0.6 on 2020-06-05 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aphor', '0004_remove_miniblog_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniblog',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aphor.UploadModel', verbose_name='图集'),
        ),
        migrations.AlterField(
            model_name='miniblog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='miniblog_set', to=settings.AUTH_USER_MODEL, verbose_name='发布用戶'),
        ),
    ]
